# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          path: ~/python

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        working-directory: ./python
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        working-directory: ./python
        run: |
          poetry check
          poetry run black . --check
          poetry run mypy .
          poetry run flake8 .

      - name: Unit Tests
        working-directory: ./python
        run: |
          poetry run pytest tests
